'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from './registry'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Get Linked</title>
      <body className={inter.className}>
      <StyledComponentsRegistry>
        <Navbar />
          {children}
        <Footer />
      </StyledComponentsRegistry>
      </body>
    </html>
  )
}
